# Fuse使用示例

本示例将演示从opeml下载公开数据集，然后利用Fuse工具对该数据集进行自动特征工程处理的流程。

### 1. 下载公开数据集

#### 下载公开测试数据hill_valley，数据集来源：
Author: Lee Graham, Franz Oppacher
Source: [UCI](http://archive.ics.uci.edu/ml/datasets/hill-valley)
Please cite:

Each record represents 100 points on a two-dimensional graph. When plotted in order (from 1 through 100) as the Y coordinate, the points will create either a Hill (a “bump” in the terrain) or a Valley (a “dip” in the terrain).
See the original source for some examples of these graphs.

In the original form, there are six files. This is the non-noisy version, with training and test sets merged.

#### Attribute Information:

1-100: Labeled “V##”. Floating point values (numeric), the Y-values of the graphs.
101: Labeled “class”. Binary {0, 1} representing {valley, hill}

In [1]:
import requests

url = 'https://www.openml.org/data/get_csv/1590101/php3isjYz'
r = requests.get(url, allow_redirects=True)
open('./valley.csv', 'wb').write(r.content)

836822

### 2. 加载公开数据集

In [2]:
import pandas as pd
file_path = "./valley.csv"
df = pd.read_csv(file_path)
df

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V92,V93,V94,V95,V96,V97,V98,V99,V100,Class
0,39.02,36.49,38.20,38.85,39.38,39.74,37.02,39.53,38.81,38.79,...,36.62,36.92,38.80,38.52,38.07,36.73,39.46,37.50,39.10,0
1,1.83,1.71,1.77,1.77,1.68,1.78,1.80,1.70,1.75,1.78,...,1.80,1.79,1.77,1.74,1.74,1.80,1.78,1.75,1.69,1
2,68177.69,66138.42,72981.88,74304.33,67549.66,69367.34,69169.41,73268.61,74465.84,72503.37,...,73438.88,71053.35,71112.62,74916.48,72571.58,66348.97,71063.72,67404.27,74920.24,1
3,44889.06,39191.86,40728.46,38576.36,45876.06,47034.00,46611.43,37668.32,40980.89,38466.15,...,42625.67,40684.20,46960.73,44546.80,45410.53,47139.44,43095.68,40888.34,39615.19,0
4,5.70,5.40,5.28,5.38,5.27,5.61,6.00,5.38,5.34,5.87,...,5.17,5.67,5.60,5.94,5.73,5.22,5.30,5.73,5.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,13.00,12.87,13.27,13.04,13.19,12.53,14.31,13.33,13.63,14.55,...,12.48,12.15,13.15,12.35,13.58,13.86,12.88,13.87,13.51,1
1208,48.66,50.11,48.55,50.43,50.09,49.67,48.95,48.65,48.63,48.61,...,46.93,49.61,47.16,48.17,47.94,49.81,49.89,47.43,47.77,0
1209,10160.65,9048.63,8994.94,9514.39,9814.74,10195.24,10031.47,10202.28,9152.99,9591.75,...,9068.11,9191.80,9275.04,9848.18,9074.17,9601.74,10366.24,8997.60,9305.77,1
1210,34.81,35.07,34.98,32.37,34.16,34.03,33.31,32.48,35.63,32.48,...,32.76,35.03,32.89,31.91,33.85,35.28,32.49,32.83,34.82,1
1211,8489.43,7672.98,9132.14,7985.73,8226.85,8554.28,8838.87,8967.24,8635.14,8544.37,...,8609.73,9209.48,8496.33,8724.01,8219.99,8550.86,8679.43,8389.31,8712.80,0

### 3. 调用Fuse进行自动特征工程

In [3]:
import fuse
fuse_af = fuse.AutoFeature()
out_df = fuse_af.fit_transform(
    df,
    index_column=None,
    label_column="Class",
)
out_df

Summarize dataset:   0%|          | 0/109 [00:00<?, ?it/s]

Summarize dataset:   0%|          | 0/109 [00:00<?, ?it/s]

Can not find primitve alias general in primitive type log
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[FUSE Pipeline] ............................... missing, total=   0.0s
[FUSE Pipeline] ................................ unique, total=   0.0s
[FUSE Pipeline] .............................. datetime, total=   0.0s
[FUSE Pipeline] .............................. encoding, total=   0.0s
[FUSE Pipeline] .................. feature_preprocessor, total=   0.0s
Generated 98 new

unary generation:  22%|██▏       | 45/205 [00:00<00:00, 448.62it/s]

[FUSE Pipeline] ............................... cluster, total=   1.4s
[FUSE Pipeline] ................................. group, total=   0.0s

[FUSE Pipeline] ................................. unary, total=   0.2s
[FUSE Pipeline] ................................ binary, total=   0.2s
[FUSE Pipeline] ..................... feature_generator, total=   2.3s
[FUSE Pipeline] ........................... correlation, total=   3.9s

unary generation:  19%|█▊        | 38/205 [00:00<00:00, 376.76it/s]

[FUSE Pipeline] .................................. fire, total=   3.5s
[FUSE Pipeline] ...................... feature_selector, total=   7.3s
[FUSE Transform] .............................. missing, total=   0.0s
[FUSE Transform] ............................... unique, total=   0.0s
[FUSE Transform] ............................. datetime, total=   0.0s
[FUSE Transform] ............................. encoding, total=   0.0s
[FUSE Transform] ................. feature_preprocessor, total=   0.0s
[FUSE Transform] .............................. cluster, total=   0.0s
[FUSE Transform] ................................ group, total=   0.0s

[FUSE Transform] ................................ unary, total=   0.2s
[FUSE Transform] ............................... binary, total=   0.1s
[FUSE Transform] .................... feature_generator, total=   0.4s
[FUSE Transform] .......................... correlation, total=   0.0s
[FUSE Transform] ................................. fire, total=   0.0s
[FUSE Transform] ..................... feature_selector, total=   0.0s

,V1,"BINARY_DIVIDE(V52, V96)","BINARY_DIVIDE(V100, V36)","BINARY_DIVIDE(V1, V80)","BINARY_DIVIDE(V80, V97)","BINARY_DIVIDE(V70, V95)","BINARY_DIVIDE(V100, V21)","BINARY_DIVIDE(V1, V43)","BINARY_DIVIDE(V57, V96)","BINARY_DIVIDE(V23, V4)",...,V91,V92,V93,V94,V95,V96,V97,V98,V99,V100
0,39.02,0.938797,1.076542,1.005929,1.056085,0.996885,1.055046,1.121909,0.933018,0.937709,...,37.57,36.62,36.92,38.80,38.52,38.07,36.73,39.46,37.50,39.10
1,1.83,1.005747,0.976879,1.051724,0.966667,0.948276,0.845000,0.994565,0.936782,1.129944,...,1.71,1.80,1.79,1.77,1.74,1.74,1.80,1.78,1.75,1.69
2,68177.69,0.972617,1.087047,0.747583,1.374512,0.933898,1.037759,1.013516,0.963750,0.963773,...,69384.71,73438.88,71053.35,71112.62,74916.48,72571.58,66348.97,71063.72,67404.27,74920.24
3,44889.06,1.024446,0.934136,1.080363,0.881427,1.018239,1.470148,1.008725,1.076774,0.900324,...,47653.60,42625.67,40684.20,46960.73,44546.80,45410.53,47139.44,43095.68,40888.34,39615.19
4,5.70,1.001745,1.138728,1.310345,0.833333,0.951178,1.100559,1.023339,0.993019,1.055762,...,5.52,5.17,5.67,5.60,5.94,5.73,5.22,5.30,5.73,5.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,13.00,0.931517,1.053822,0.941347,0.996392,1.106073,0.917799,0.929900,0.992636,1.125767,...,12.89,12.48,12.15,13.15,12.35,13.58,13.86,12.88,13.87,13.51
1208,48.66,0.998331,0.959044,1.090298,0.896005,0.977372,0.966026,0.964328,1.037338,0.950823,...,47.45,46.93,49.61,47.16,48.17,47.94,49.81,49.89,47.43,47.77
1209,10160.65,1.051730,0.987861,1.030478,1.026911,1.176759,0.878816,1.129943,1.006686,1.101938,...,10413.41,9068.11,9191.80,9275.04,9848.18,9074.17,9601.74,10366.24,8997.60,9305.77
1210,34.81,1.038996,0.999139,1.014277,0.972789,1.061109,0.826686,0.972346,1.062038,1.242508,...,33.18,32.76,35.03,32.89,31.91,33.85,35.28,32.49,32.83,34.82
1211,8489.43,0.973010,0.972954,1.046250,0.948928,1.015418,1.030874,1.188423,1.034949,1.101410,...,7747.70,8609.73,9209.48,8496.33,8724.01,8219.99,8550.86,8679.43,8389.31,8712.80

### 4. 模型训练

#### 对生成特征进行建模测试
这里我们分别将原始特征和Fuse生成特征做7:3的训练/测试集切分，然后利用默认的xgboost分类器分别对二者的训练集数据进行训练，然后在测试集上进行测试，并评估模型再测试集上的AUC，用于对比Fuse生成特征的效果。

In [4]:
import re
import numpy as np
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score


def split_data(train_df, index, label):
    regex = re.compile(r"\[|\]|<", re.IGNORECASE)
    
    # replace some col name that model could get error
    train_df.columns = [regex.sub("_", col) if any(x in str(col) for x in set(
        ('[', ']', '<'))) else col for col in train_df.columns.values]
    label_df = train_df[label]
    selected_cols = [x for x in train_df.columns if x != index and x != label]
    input_df = train_df[selected_cols]
    X_train, X_test, y_train, y_test = train_test_split(
        input_df, label_df, test_size=0.3, random_state=11,
        stratify=label_df.to_numpy())
    return X_train, X_test, y_train, y_test


def test_auc(X_train, X_test, y_train, y_test):
    """Calculate the auc by using default XGBClassifier."""
    
    model = XGBClassifier(random_state=11)
    model.fit(X_train, y_train)
    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = np.where(y_prob >= 0.5, 1, 0)
    y_pred = model.predict(X_test)
    auc = accuracy_score(y_test, y_pred)
    return auc

def compare(raw_df, fuse_df, index, label):
    X_train, X_test, y_train, y_test = split_data(raw_df, index, label)
    raw_auc = test_auc(X_train, X_test, y_train, y_test)
    #
    X_train, X_test, y_train, y_test = split_data(fuse_df, index, label)
    fuse_auc = test_auc(X_train, X_test, y_train, y_test)
    print("########################")
    print("Test result for compare raw & fuse feature on xgboost auc.")
    print("Raw feature AUC: {}".format(raw_auc))
    print("Fuse feature AUC: {}".format(fuse_auc))
    print("########################")

In [5]:
compare(df, out_df, index=None, label="Class")

########################
Test result for compare raw & fuse feature on xgboost auc.
Raw feature AUC: 0.532967032967033
Fuse feature AUC: 0.8763736263736264
########################